// Code generated by goctl. DO NOT EDIT.
package types

type DeviceListRequest struct {
	Page int    `json:"page,optional"`
	Size int    `json:"size,optional"`
	Name string `json:"name,optional"`
}

type DeviceListBasic struct {
	Identity    string `json:"identity"`
	Name        string `json:"name"`
	Key         string `json:"key"`
	Secret      string `json:"secret"`
	ProductName string `json:"product_name"`
}

type DeviceListReply struct {
	List  []*DeviceListBasic `json:"list"`
	Count int64              `json:"count"`
}
